services:
  kyc:
    container_name: 'kyc'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    hostname: kyc
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=${DATA_SOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${JPA_HIBERNATE_DDL_AUTO}
    user: "spring:spring"
    networks:
      - kyc-net
    ports:
      - "8080:8080"
    env_file:
      - .env
networks:
  kyc-net:
