services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    hostname: postgres
    restart: unless-stopped
    depends_on:
      - postgres
    user: "spring:spring"
    networks:
      - kyc-net
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/postgresql:/var/lib/postgresql/data
    env_file:
      - .env
  app:
    container_name: 'app'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    hostname: app
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=${DATA_SOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${JPA_HIBERNATE_DDL_AUTO}
    user: "spring:spring"
    networks:
      - kyc-net
    ports:
      - "8080:8080"
    env_file:
      - .env
networks:
  kyc-net:
